-- Migration 004: Invoice records
-- Stores verifiable invoice data for each completed job.
-- invoice_id is a UUID generated by the application layer.
-- settlement_hash is SHA-256 of canonical invoice fields for tamper evidence.

CREATE TABLE IF NOT EXISTS invoices (
  invoice_id      TEXT PRIMARY KEY,                -- UUID
  job_id          TEXT NOT NULL UNIQUE,            -- references jobs.job_id
  renter_id       INTEGER NOT NULL,                -- references renters.id
  provider_id     INTEGER,                         -- references providers.id (NULL if no provider)
  amount_usd      REAL NOT NULL,                   -- gross total in USD
  sar_equivalent  REAL NOT NULL,                   -- amount_usd * 3.75 (fixed peg)
  settlement_hash TEXT NOT NULL,                   -- SHA-256 tamper-evidence hash
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_invoices_renter    ON invoices(renter_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_job       ON invoices(job_id);
CREATE INDEX IF NOT EXISTS idx_invoices_provider  ON invoices(provider_id, created_at DESC);
